name: IaC Security

permissions:
  contents: read
  actions: read

on:
  push:
    branches: [ main, master ]
  pull_request:

env:
  TF_IN_AUTOMATION: "true"
  CHECKOV_HARD_FAIL_ON: "HIGH,CRITICAL"

jobs:
  terraform_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Fmt
        run: terraform fmt -recursive -check

      - name: Terraform Init (no backend)
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

  tflint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: TFLint Init
        run: tflint --init

      - name: TFLint Run
        run: tflint

  checkov:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Checkov
        run: pip install checkov

      # Genera SARIF pero NUNCA falla el paso (para que el job no se pinche cuando no hay findings)
      - name: Run Checkov (SARIF, no-fail)
        run: |
          checkov -d . \
            --framework terraform,github_actions \
            --output sarif \
            --output-file-path results.sarif || true

      - name: Upload SARIF to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      # Gate real: falla solo si hay HIGH/CRITICAL
      - name: Run Checkov gate (fail on HIGH/CRITICAL)
        run: |
          checkov -d . \
            --framework terraform,github_actions \
            --quiet \
            --hard-fail-on "${CHECKOV_HARD_FAIL_ON}"
