name: IaC Security

on:
  push:
    branches: [ main, master ]
  pull_request:

env:
  TF_IN_AUTOMATION: "true"
  CHECKOV_HARD_FAIL_ON: "HIGH,CRITICAL"  # adjust to "CRITICAL" if needed

jobs:
  terraform_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Fmt
        run: terraform fmt -recursive -check

      - name: Terraform Init (no backend)
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

  tflint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: TFLint Init
        run: tflint --init

      - name: TFLint Run
        run: tflint

  checkov:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write   # allow SARIF upload
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov (fail on HIGH/CRITICAL)
        run: |
          checkov -d . --quiet --output sarif --output-file-path results.sarif
          # Hard fail on severity threshold by scanning again with exit code
          if ! checkov -d . --quiet --hard-fail-on $CHECKOV_HARD_FAIL_ON; then
            echo "Checkov found HIGH/CRITICAL issues."
            EXIT_CODE=1
          else
            EXIT_CODE=0
          fi
          echo "EXIT_CODE=$EXIT_CODE" >> $GITHUB_ENV

      - name: Upload SARIF to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      - name: Fail if threshold exceeded
        if: env.EXIT_CODE == '1'
        run: exit 1
